web:
    build: .
    ports:
     - "127.0.0.1:8080:8080"
    links: 
     - db:db   
    container_name: todo-app-mongo 
db:
    image: dockerfile/mongodb
    ports:
     - "127.0.0.1:27017:27017"
    container_name: todo-mongo
