web:
    build: .
    ports:
     - "127.0.0.1:8080:8080"
    links: 
     - db:db   
    container_name: todo-app 
db:
    image: postgres:9.1.18
    ports:
     - "127.0.0.1:5432:5432"
    container_name: todo-db   
